### PR TITLE
Update neuroparc atlas names

### PR DESCRIPTION
**Pull request by Lawreros**
Hello C-PAC team,
In preparation for publication, the neuroparc repository will soon be overhauled/reorganized for clarity (the [update branch](https://github.com/neurodata/neuroparc/tree/paper-fixes) is ready to be merged with the master branch). This has resulted in the renaming of a few files that are used by various configurations in C-PAC. This PR updates those names, and upon approval I will update neuroparc ASAP.
Let me know if you have any questions/suggestions. Thanks!

### CODE REVIEW

**Comment by sgiavasis** [comment]
Hello @Lawreros,

Awesome! Thank you for this proactive update!

**Comment by sgiavasis** [comment]
Could you rebase this off of the current develop branch? We'd like to kick off some tests before merging this to Master, but rebasing this PR brings along some other commits.

**Comment by Lawreros** [comment]
I think I have successfully rebased it (first time rebasing, so let me know if I haven't). Is the issue with Singularity something I can solve on my end?

**Comment by sgiavasis** [comment]
Nope, all set. Thanks again.
I'm pulling into our develop branch. When we release this upcoming version (1.7), we merge to Master.
I will let you know when we do this, in this thread.

**Comment by SucyLi** [comment]
Hi @Lawreros, we just released C-PAC 1.7. Could you please update neuroparc atlas names on your end?

**Pull request merged**
