### PR TITLE
🔨 Use `maxCoresPerParticipant` and `numParticipantsAtOnce`

### PR DESCRIPTION
**Pull request by shnizzedy**
> I'm having some issues setting up the pipeline. I think the most urgent one is that I'm not able to use multiple cores and subjects when modified the yml default pipeline
> 
> I edited the standard pipeline to increase number of subjects in parallel and cores. While is picking up the name of the pipeline (which I changed to TESTPIPELINE), is still only using one core and one subject at a time

― [CPAC Docker/Singularity not picking configutation files options + wxpython singularity](https://groups.google.com/forum/#!topic/cpax_forum/aNYf6nwRTiI)

It looks like we're currently specifically overwriting those values unconditionally: https://github.com/FCP-INDI/C-PAC/blob/3be7349b29fbc0871582b7cfe63ee87a576d978b/dev/docker_data/run.py#L395-L400

This PR will take the values from the config unless there's a `--pipeline_override` for either of them.

### CODE REVIEW

**Comment by sgiavasis** [comment]
The --n_cpus is a hold-over from the original initialization of C-PAC as a BIDS-App, via the BIDS-Apps spec I believe.

I can't tell exactly- does this remove need for usage of --n_cpus entirely, and now replaced with `--pipeline_override maxCoresPerParticipant: etc.` ?

**Comment by shnizzedy** [comment]
`pipeline_override maxCoresPerParticipant`  doesn't replace `n_cpus`, just uses the override if present. I switched this PR back to draft status to make sure `n_cpus` is a hard limit before we merge it in though,

**Comment by shnizzedy** [comment]
Also, the defaults _are_ all `1`s right now:

https://github.com/FCP-INDI/C-PAC/blob/66c5695b2e8dae46361d2ffb532fb52144f393a5/dev/docker_data/default_pipeline.yml#L34-L43

https://github.com/FCP-INDI/C-PAC/blob/3be7349b29fbc0871582b7cfe63ee87a576d978b/dev/docker_data/run.py#L186

https://github.com/FCP-INDI/C-PAC/blob/3be7349b29fbc0871582b7cfe63ee87a576d978b/dev/docker_data/run.py#L396-L399

@ccraddock @sgiavasis should we bump those defaults up and let users set them lower if needed?

**Comment by sgiavasis** [comment]
I believe @ccraddock mentioned 6-8 CPUs per participant, and 16 GB memory.

If we want to go with a safer lower bound, I think something like 2 or 3 CPUs, and 8 GB of memory. And keeping num participants at once as 1.

**Comment by shnizzedy** [comment]
`num_ants_threads` is currently set to the minimum of `num_ants_threads` or `n_cpus`.

https://github.com/FCP-INDI/C-PAC/blob/cebbd4b54186761bca41714a3eff5afa1cd7ed85/dev/docker_data/run.py#L405

Is this fine or should it be divided by `numParticipantsAtOnce`?

**Comment by sgiavasis** [comment]
> `num_ants_threads` is currently set to the minimum of `num_ants_threads` or `n_cpus`.
> 
> https://github.com/FCP-INDI/C-PAC/blob/cebbd4b54186761bca41714a3eff5afa1cd7ed85/dev/docker_data/run.py#L405
> 
> Is this fine or should it be divided by `numParticipantsAtOnce`?

That's fine- this is basically to clip num_ants_threads to not exceed n_cpus.

Dividing by numParticipantsAtOnce- would that be in a move to tie that into the --n_cpus parameter?

**Comment by shnizzedy** [comment]
> Dividing by numParticipantsAtOnce- would that be in a move to tie that into the --n_cpus parameter?

Yeah, I'm concerned that `num_ants_threads` would effectively be multiplied by `numParticipantsAtOnce` (because that number of participants would be running in parallel), so `num_ants_threads` could easily exceed `n_cpus` if capped without regard to `numParticipantsAtOnce`

**Comment by sgiavasis** [comment]
I had a bit of pause here, because we're at a fork regarding how to approach the parallelization of participant pipelines.

Eventually, it would be great to include functionality in the C-PAC wrapper package to launch multiple Docker containers, one for each participant pipeline. This would need quite a bit of planning (and also, how would things like longitudinal factor in?). This would definitely be later- not looking for a massive jump into scope creep right now.

So for now, we can stick with numParticipantsAtOnce still being a thing. But looking at how C-PAC would be used once the launcher can launch multiple containers at once- users would still have to set num CPUs per container, with the knowledge/decision of how many containers they want running in parallel anyway.

What if we keep --n_cpus to numCoresPerParticipant (and maybe name the --n_cpus flag better), and introduce, at least for now, another flag for the amount of participants at once? And in the near future, we can remove those keys from the pipeline config altogether, having them replaced at the CLI level. Thoughts?

**Comment by shnizzedy** [comment]
I think we should probably open an epic in the icebox or backlog for launching multiple containers from the wrapper.

And I think `--n_cpus` is fine as a flag since it's defined pretty well in the helpstring, especially if we (eventually) get rid of the overlapping `maxCoresPerParticipant` in the config and have a reasonable hierarchy for which to use in the meantime.

This PR would set that hierarchy like this (most preferred to least):
1. `--n_cpus {n}` on the commandline
2. `--pipeline_override="maxCoresPerParticipant {n}"` on the commandline
3. `maxCoresPerParticipant: {n}` from config
4. `3`

**Comment by sgiavasis** [comment]
> I think we should probably open an epic in the icebox or backlog for launching multiple containers from the wrapper.

Agreed.

The hierarchy you listed sounds perfect. All good!

**Pull request merged**
