### PR TITLE
🔧 Update linking libGL and libgsl for Singularity builds from Docker images

### PR DESCRIPTION
**Pull request by shnizzedy**
#1289 + #1268 as a hotfix

### CODE REVIEW

**Comment by shnizzedy** [comment]
If we want a hotfix for the AFNI/Singularity issue, this PR is #1289 without the tests + #1268, based on [master](https://github.com/FCP-INDI/C-PAC/tree/master) instead of [develop](https://github.com/FCP-INDI/C-PAC/tree/develop).

**Comment by sgiavasis** [comment]
I think these two issues warrant a hotfix, despite v1.7 release nearing.

@shnizzedy - could you kick off a run of this hotfix branch using the fmriprep-options preconfig, and correlate with v1.6.2 with the same preconfig? I will run it on some of the new regtest configs also.

Mainly for sanity check and to make sure nothing else was broken- then we can safely merge to Master.

**Comment by sgiavasis** [comment]
Regtest-1 pipeline, a `calc_motion_parameters` error on this branch:

```
File: /output/crash/crash-20200603-205729-root-calc_motion_parameters.b0-da2f391f-4ccf-47a9-80f3-50f91f9a6998.pklz
Node: resting_preproc_1019436_1.gen_motion_stats_None_None_None_1.calc_motion_parameters
Working directory: /output/working/resting_preproc_1019436_1/gen_motion_stats_None_None_None_1/_scan_rest_acq-1_run-1/calc_motion_parameters


Node inputs:

function_str = CPAC.generate_motion_statistics.generate_motion_statistics.gen_motion_parameters
max_displacement = /output/working/resting_preproc_1019436_1/func_preproc_afni_mean_3dvolreg_0/_scan_rest_acq-1_run-1/func_motion_correct_3dvolreg/max_displacement.1D
motion_correct_tool = None
movement_parameters = /output/working/resting_preproc_1019436_1/func_preproc_afni_mean_3dvolreg_0/_scan_rest_acq-1_run-1/func_motion_correct_3dvolreg/sub-1019436_ses-1_task-rest_acq-1_run-1_bold_calc_tshift_resample.1D
scan_id = rest_acq-1_run-1
subject_id = 1019436_1



Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function.py", line 152, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/generate_motion_statistics/generate_motion_statistics.py", line 429, in gen_motion_parameters
    ('Mean_Relative_Maxdisp', avg_relative(maxdisp)), # to be updated
UnboundLocalError: local variable 'maxdisp' referenced before assignment
```

**Comment by sgiavasis** [comment]
Regtest-1 pipeline, `calculate_FDJ` error also:

```
File: /output/crash/crash-20200603-204148-root-calculate_FDJ-625a1f8f-e72c-48f5-84d7-e4de69446db0.pklz
Node: resting_preproc_1019436_1.gen_motion_stats_None_None_None_0.calculate_FDJ
Working directory: /output/working/resting_preproc_1019436_1/gen_motion_stats_None_None_None_0/calculate_FDJ


Node inputs:

function_str = CPAC.generate_motion_statistics.generate_motion_statistics.calculate_FD_J
in_file = <undefined>
motion_correct_tool = None



Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 69, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function.py", line 152, in _run_interface
    out = function_handle(**args)
TypeError: calculate_FD_J() missing 1 required positional argument: 'in_file'
```

**Comment by sgiavasis** [comment]
@shnizzedy - wanted to double-check here- the fmriprep-options preconfig run completed successfully?

**Comment by shnizzedy** [comment]
@sgiavasis yep, and the correlations of this PR in Singularity vs 1.6.2 in Docker with the the fmriprep-options preconfig look like this:
heatmap

**Comment by sgiavasis** [comment]
Okay, all other runs look great as well. We all good on merging this in? Last call.

**Pull request merged**
