### PR TITLE
🚚 Move C-PAC generated configs into `log/sub-${sub}_ses-${ses}` subdirectory

### PR DESCRIPTION
**Pull request by shnizzedy**
## Related to

Related to #1774, #1775, #1776 & #1777 by @shnizzedy 

## Description

After updating the output directory structure so that `log`, `output` and `working` have matching subdirectories (#1775) and adding a data-config hash to C-PAC generated config filenames (#1777), move those generated config files from the top of the output tree into the `log/sub-${sub}_ses-${ses}`

## Technical details

https://github.com/FCP-INDI/C-PAC/blob/f3aefca12e4d1c47d9a6251e52d05460a4fc4db9/dev/docker_data/run.py#L741-L743

## Tests

https://github.com/FCP-INDI/C-PAC/blob/f3aefca12e4d1c47d9a6251e52d05460a4fc4db9/CPAC/utils/configuration.py#L481-L494 https://github.com/FCP-INDI/C-PAC/blob/d50f8daa167c4f1834617d6cc70fb436d78f5e5d/CPAC/utils/configuration/configuration.py#L374-L386

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
We could stop at https://github.com/FCP-INDI/C-PAC/pull/1778/commits/2ed4d6a5d27a4df4a9668a2cd20effdcc0c50cbc if we want to limit the number of copies of a config file to 1, ie go from `./cpac_*_config_${hash}_${timestamp}.yml` to `./log/pipeline_${pipeline_name}/cpac_*_config_${hash}_${timestamp}.yml` instead of to `./log/pipeline_${pipeline_name}/sub-${sub}_ses-${ses}/cpac_*_config_${hash}_${timestamp}.yml`

**Comment by shnizzedy** [comment]
Also, I wonder if we should make these config files read-only?

**Comment by sgiavasis** [comment]
> Also, I wonder if we should make these config files read-only?

Good idea!

**Comment by shnizzedy** [comment]
> > Also, I wonder if we should make these config files read-only?
> 
> Good idea!

:rocket: 

https://github.com/FCP-INDI/C-PAC/blob/55667a2f12cadda692cd0a4b404a71b71660ebc0/dev/docker_data/run.py#L740-L742

**Comment by sgiavasis** [comment]
> > > Also, I wonder if we should make these config files read-only?
> > 
> > 
> > Good idea!
> 
> 🚀
> 
> https://github.com/FCP-INDI/C-PAC/blob/55667a2f12cadda692cd0a4b404a71b71660ebc0/dev/docker_data/run.py#L740-L742

_Yee_ nice

**Review by sgiavasis — APPROVED** [review]

**Pull request merged**
