### PR TITLE
📝 List available preconfigs in usage string

### LINKED ISSUE #1680: 📝 List available preconfigs in usage string
### Related problem

The only way I know to see all available preconfigs is to try to run with `--preconfig` and the name of a non-existent preconfig ([C-PAC latest documentation » User Documentation » Setting Up A Pipeline Configuration » Pre-configured Pipelines](https://fcp-indi.github.io/docs/latest/user/pipelines/preconfig) has those that are documented)

### Proposed feature

Include a list of available preconfigs in the usage string for the `--preconfig` flag

### Acceptance criteria

- [x] list of available preconfigs included in the usage string for the `--preconfig` flag

### Alternatives

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shnizzedy**
## Fixes

Fixes #1680 by @shnizzedy

## Description

Updates `--preconfig` section of help string to

```BASH
  --preconfig PRECONFIG
                        Name of the preconfigured pipeline to run. Available
                        preconfigured pipelines: ['abcd-options', 'anat-only',
                        'blank', 'ccs-options', 'fmriprep-options', 'fx-
                        options', 'monkey', 'monkey-ABCD', 'ndmg', 'nhp-
                        macaque', 'preproc', 'rbc-options', 'rodent']. See
                        https://fcp-
                        indi.github.io/docs/nightly/user/pipelines/preconfig
                        for more information about the preconfigured
                        pipelines.
```

from

```BASH
  --preconfig PRECONFIG
                        Name of the pre-configured pipeline to run.
```

## Technical details

* Moves the gathering of available preconfigured pipelines from [checking if the pipeline is a preconfigured option](https://github.com/FCP-INDI/C-PAC/blob/a9025ff8c64b8c18712263f6c5dba5106336ee2c/CPAC/utils/utils.py#L1470-L1479) to   [an importable global variable](https://github.com/FCP-INDI/C-PAC/blob/10b1d324beb3639bd9bb082c20d13b3031de0687/CPAC/pipeline/__init__.py#L5-L12) and uses that variable for both the check and the usage string
* The URL should direct to nightly docs for development images and versioned docs for releases.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [x] I added or updated documentation (this is a documentation update).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
Do we want to do anything to differentiate the `benchmark-*`, `blank` and `regtest-*` preconfigs from the others? Do we want to include them in this list at all?

**Comment by shnizzedy** [comment]
> Can you clarify for me the function of the `benchmark-*` and `blank` preconfigs?

* The `benchmark-*` preconfigs are included in the user docs [here](https://fcp-indi.github.io/docs/v1.8.3/user/pipelines/preconfig#benchmark-ants-c-pac-benchmark-with-ants-registration)
* `blank` is intended for if you don't want to start [`FROM: default`](https://fcp-indi.github.io/docs/latest/user/pipelines/pipeline_config#using-a-text-editor), but instead specify every item you want (we should add this to the docs, and https://github.com/FCP-INDI/C-PAC/issues/1560)

**Comment by gkiar** [comment]
Excellent, huge help, thank you! I think we want to remove `benchmark` and `regtest` preconfigs from this tooltip, but leave `blank` — running a blank pipeline config is kind of a nice way to validate a data config, no?

**Comment by shnizzedy** [comment]
Updated to

```BASH
  --preconfig PRECONFIG
                        Name of the preconfigured pipeline to run. Available
                        preconfigured pipelines: ['abcd-options', 'anat-only',
                        'blank', 'ccs-options', 'fmriprep-options', 'fx-
                        options', 'monkey', 'monkey-ABCD', 'ndmg', 'nhp-
                        macaque', 'preproc', 'rbc-options', 'rodent']. See
                        https://fcp-
                        indi.github.io/docs/nightly/user/pipelines/preconfig
                        for more information about the preconfigured
                        pipelines.
```

from

```BASH
  --preconfig PRECONFIG
                        Name of the preconfigured pipeline to run. Available
                        preconfigured pipelines: ['abcd-options', 'anat-only',
                        'benchmark-ANTS', 'benchmark-FNIRT', 'blank', 'ccs-
                        options', 'fmriprep-options', 'fx-options', 'monkey',
                        'monkey-ABCD', 'ndmg', 'nhp-macaque', 'preproc', 'rbc-
                        options', 'regtest-1', 'regtest-2', 'regtest-3',
                        'regtest-4', 'rodent']. See https://fcp-
                        indi.github.io/docs/nightly/user/pipelines/preconfig
                        for more information about the preconfigured
                        pipelines.
```

in 793a5ce

**Comment by sgiavasis** [comment]
Just to reiterate what I said in person earlier 😄 - `benchmark-FNIRT` is the only benchmark we'd like to keep "official" for now.

**Review by sgiavasis — DISMISSED** [review]

**Comment by shnizzedy** [comment]
```Python
  --preconfig PRECONFIG
                        Name of the preconfigured pipeline to run. Available
                        preconfigured pipelines: ['abcd-options', 'anat-only',
                        'benchmark-FNIRT', 'blank', 'ccs-options', 'fmriprep-
                        options', 'fx-options', 'monkey', 'monkey-ABCD',
                        'ndmg', 'nhp-macaque', 'preproc', 'rbc-options',
                        'rodent']. See https://fcp-
                        indi.github.io/docs/nightly/user/pipelines/preconfig
                        for more information about the preconfigured
                        pipelines.
```

**Pull request merged**
