### PR TITLE
Add auto format pre-commit hooks

### PR DESCRIPTION
**Pull request by nx10**
## Description

This PR adds [pre-commit](https://pre-commit.com/) hooks for [isort](https://github.com/PyCQA/isort) and [black](https://github.com/psf/black) to sort includes and format python files.

It will run on a per-file basis, but `pre-commit run --all-files` should be run to format the entire repository once before/directly after this is merged.

There might be other useful hooks for formatting YAML files or removing unused imports that might be worth looking into in the future ([pycln](https://github.com/hadialqattan/pycln) segfaulted with CPAC for me).

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
I vote we
- [ ] add an `.isort.cfg` file
- [ ] drop `.flake8` and `.pylintrc` since we're adopting `black`

In the proposed `.isort.cfg`, I'd put
```INI
[settings]
; black-compatible options, ref https://pycqa.github.io/isort/docs/configuration/profiles.html#black
profile=black

; sections
; packages we've contributed to
known_collab=nibabel,nilearn,nipype,PyBASC,pybids,scipy,spython
; our packages that aren't this one
known_other_first_party=flowdump,indi_aws,indi_schedulers,PyPEER
; this package
known_first_party=CPAC
; default sequence with COLLAB and OTHER_FIRST_PARTY inserted between third- and first-party
sections=FUTURE,STDLIB,THIRDPARTY,COLLAB,OTHER_FIRST_PARTY,FIRSTPARTY,LOCALFOLDER

; house style
atomic=true
combine_as_imports=true
force_sort_within_sections=true
honor_noqa=true
order_by_type=false
remove_redundant_aliases=true
star_first=true
```

(the `isort` options are defined [here](https://pycqa.github.io/isort/docs/configuration/options.html))

I'm happy to be outvoted on any particular style point, but I think we should take the opportunity to choose the style options we want before we do the big `black` + `isort` run.

(Also, I think we'll need to do a little manual checking of quirks that arise from that style-run before we merge the changes in, like if the first import gets moved down in a file with a license notice comment, the last section of license notice comment is going to be attached to that import lower in the file instead of staying above all the code)

I'm so excited to tidy up this whole codebase. Thanks for setting up the hooks!

**Comment by shnizzedy** [comment]
If we use Ruff instead of black + isort, here's my suggestion for a first iteration of a `.ruff.toml`:

```TOML
extend-exclude=["dev/docker_data/get-pip_23.0.1.py"]
extend-select = ["A", "C4", "D", "G", "I", "ICN", "NPY", "PL", "RET", "RSE", "RUF", "Q", "T20", "W"]
# variants still use 3.7
target-version = "py37"

[per-file-ignores]
"CPAC/func_preproc/func_preproc.py" = ["E402"]

[lint.flake8-import-conventions.extend-aliases]
"CPAC.pipeline.cpac_group_runner" = "cgr"
"nibabel" = "nib"
"nipype.interfaces.io" = "nio"
"networkx" = "nx"
"pkg_resources" = "p"
"CPAC.pipeline.nipype_pipeline_engine" = "pe"

[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["CPAC"]
no-lines-before = ["collab", "other-first-party", "local-folder"]
order-by-type = true
section-order = ["future", "standard-library", "third-party", "collab", "other-first-party", "first-party", "local-folder"]

[lint.isort.sections]
"collab" = ["nibabel", "nilearn", "nipype", "PyBASC", "pybids", "scipy", "spython"]
"other-first-party" = ["flowdump", "indi_aws", "indi_schedulers", "PyPEER"]

[lint.pydocstyle]
convention = "numpy"
ignore-decorators = ["CPAC.utils.docs.docstring_parameter"]

[lint.pylint]
max-args = 10
max-branches = 50
max-returns = 12
max-statements = 100

[lint.pyupgrade]
# Until variants Python ≥ 3.10
keep-runtime-typing = true
```

(and still drop `.flake8` and `.pylintrc`)

**Comment by nx10** [comment]
There was some discussion a while ago about dropping builds of new images for the variants (old versions can still be used indefinitely, maintenance effort continues to increase, ...)

Would it make sense to drop the old variants after this release so this PR can target 3.11?

**Comment by shnizzedy** [comment]
> Would it make sense to drop the old variants after this release so this PR can target 3.11?

― https://github.com/FCP-INDI/C-PAC/pull/1882#issuecomment-1875627656

Good question. I'm all for dropping the every-release variants after this release and just creating them as we need them in the future. @sgiavasis? @gkiar?

**Pull request closed without merging**
