### PR TITLE
✏️ 🐛 Subset Numpy Array to Exclude Infinite Values Before Histogramming

### LINKED ISSUE #1194: Range parameter must be finite
Current known issue that sometimes occurs during QC image generation; has been seen in SCA and VMHC QC outputs but may not be restricted to them:

```
Traceback:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/plugins/linear.py", line 44, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 471, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 555, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python2.7/site-packages/nipype/interfaces/base/core.py", line 521, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function.py", line 158, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/qc/utils.py", line 1352, in gen_histogram
    hist_path.append(make_histogram(file_, measure))
  File "/code/CPAC/qc/utils.py", line 1395, in make_histogram
    y, binEdges = np.histogram(data_flat[data_flat != 0], bins=100)
  File "/usr/local/miniconda/lib/python2.7/site-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.
```

Respond with fix confirmation once released:
https://groups.google.com/forum/#!topic/cpax_forum/Egoor7eNDlc

### PR DESCRIPTION
**Pull request by shnizzedy**
This should squash that bug (works with toy data), but do we have a real config for which this error occurs? Should we catch and flag arrays that contain infinities?
 
Resolves #1194

### CODE REVIEW

**Comment by sgiavasis** [comment]
I believe @HechengJin0 also saw it, and may be able to provide the data and config.

**Comment by sgiavasis** [comment]
Yes, catching and flagging would be good. Also should figure out why it's happening, to provide a bit more info, potentially.

**Comment by HechengJin0** [comment]
Yes. I would like to look into this bug. https://github.com/FCP-INDI/C-PAC/issues/1193

**Comment by shnizzedy** [comment]
Yeah, this PR will trivially resolve #1193 and #1194 by plotting only finite values, but I suspect this issue is really the result of a problem upstream where infinite values are getting into the array.

**Comment by sgiavasis** [comment]
I didn't see a recurrence of this crash, but after we merge and run larger runs, we can check for it, can always pop back up.

**Pull request merged**
