### PR TITLE
🧑‍💻 Move autoversioning code from CI to pre-commit

### PR DESCRIPTION
**Pull request by shnizzedy**
## Simplifies

Simplifies autoversioning.

## Description

* Whenever the version is updated in https://github.com/FCP-INDI/C-PAC/blob/5ac6a025dd3a4a28fefaecbda4f6b961f9d0fe7e/CPAC/info.py#L43-L46, all the other appropriate places will now be updated as part of that commit via [`pre-commit`](https://pre-commit.com/) instead of waiting for the CI to handle it as a separate commit
* Whenever the dev Dockerfiles are updated, `pre-commit` will update the respective top-level Dockerfiles instead of waiting for the CI to handle it as a separate commit

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I updated the changelog.
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sgiavasis** [comment]
Very cool!

Out of curiosity what is the inline HTML rule/ `<span>` enabling for?

**Review by sgiavasis — APPROVED** [review]

**Comment by nx10** [comment]
> Very cool!
> 
> Out of curiosity what is the inline HTML rule/ `<span>` enabling for?

The badges and title are in a `<span>` in the `README.md`.

**Comment by shnizzedy** [comment]
> > Very cool!
> > Out of curiosity what is the inline HTML rule/ `<span>` enabling for?
> 
> The badges and title are in a `<span>` in the `README.md`.

<span title="GitHub Flavored Markdown" id="a-specific-point">GFM</span> allows raw HTML elements except [these](https://github.github.com/gfm/#disallowed-raw-html-extension-), but `span`'s the only one we're using here (as Flo noted / I think). I like it for dropping `id` properties into markdown too, so you can link to [a specific point](#a-specific-point) in a markdown doc.

**Comment by oga35767-eng** [comment]
Ty

**Pull request merged**
