### PR TITLE
/Fix/assign_stopidx_asend

### LINKED ISSUE #1766: 🐛 Provide user the option to assign stop_tr value as either None or End
### Describe the bug

The pipeline config mentions that the user can provide either `None` or `End` as `stop_tr`. 

```
functional_preproc:

  run: On

  truncation:

    # First timepoint to include in analysis.
    # Default is 0 (beginning of timeseries).
    # First timepoint selection in the scan parameters in the data configuration file, if present, will over-ride this selection.
    # Note: the selection here applies to all scans of all participants.
    start_tr: 0

    # Last timepoint to include in analysis.
    # Default is None or End (end of timeseries).
    # Last timepoint selection in the scan parameters in the data configuration file, if present, will over-ride this selection.
    # Note: the selection here applies to all scans of all participants.
    stop_tr: None
```
But the current script has a if condition that only checks for "None" and would throw an error if `stop_tr` is assigned a value `End`.

https://github.com/FCP-INDI/C-PAC/blob/d8add6bd4ead71775690878fc4dcde9fde329eda/CPAC/func_preproc/func_preproc.py#L577-L581

### To reproduce

1. In the pipeline config file, assign the value of `stop_tr` as `End` under `functional_preproc, truncation , stop_tr`
2. Run the CPAC with the pipeline config file that has `stop_tr` assigned as `End`.

### Preconfig

- [ ] default
- [ ] abcd-options
- [ ] anat-only
- [ ] blank
- [ ] ccs-options
- [ ] fmriprep-options
- [ ] fx-options
- [ ] monkey
- [ ] monkey-ABCD
- [ ] ndmg
- [ ] nhp-macaque
- [ ] preproc
- [ ] rbc-options
- [ ] rodent

### Custom pipeline configuration

```
%YAML 1.1
---
# CPAC Pipeline Configuration YAML file
# Version 1.8.4.dev
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

FROM: default


pipeline_setup: 
  # Name for this pipeline configuration - useful for identification.
  pipeline_name: cpac_preproc

  working_directory: 
    # Deletes the contents of the Working Directory after running.
    # This saves disk space, but any additional preprocessing or analysis will have to be completely re-run.
    remove_working_dir: Off

  system_config: 
    # Select Off if you intend to run CPAC on a single machine.
    # If set to On, CPAC will attempt to submit jobs through the job scheduler / resource manager selected below.
    on_grid: 
      SGE: 
        # SGE Parallel Environment to use when running CPAC.
        # Only applies when you are running on a grid or compute cluster using SGE.
        parallel_environment: cpac

    # The maximum amount of memory each participant's workflow can allocate.
    # Use this to place an upper bound of memory usage.
    # - Warning: 'Memory Per Participant' multiplied by 'Number of Participants to Run Simultaneously'
    #   must not be more than the total amount of RAM.
    # - Conversely, using too little RAM can impede the speed of a pipeline run.
    # - It is recommended that you set this to a value that when multiplied by
    #   'Number of Participants to Run Simultaneously' is as much RAM you can safely allocate.
    maximum_memory_per_participant: 3

    # Full path to the FSL version to be used by CPAC.
    # If you have specified an FSL path in your .bashrc file, this path will be set automatically.
    FSLDIR: FSLDIR

  Amazon-AWS: 
    # Enable server-side 256-AES encryption on data to the S3 bucket
    s3_encryption: On

anatomical_preproc: 
  # Non-local means filtering via ANTs DenoiseImage
  non_local_means_filtering:
    run: Off

  # N4 bias field correction via ANTs
  n4_bias_field_correction:
    run: On

segmentation: 
  tissue_segmentation: 
    # option parameters
    FSL-FAST: 
      use_priors: 
        # Full path to a directory containing binarized prior probability maps.
        # These maps are included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
        # It is not necessary to change this path unless you intend to use non-standard priors.
        priors_path: $FSLDIR/data/standard/tissuepriors/2mm

    Template_Based: 
      # These masks should be in the same space of your registration template, e.g. if
      # you choose 'EPI Template' , below tissue masks should also be EPI template tissue masks.
      #
      # Options: ['T1_Template', 'EPI_Template']
      template_for_segmentation: []

      # These masks are included as part of the 'Image Resource Files' package available
      # on the Install page of the User Guide.

      # Full path to a binarized White Matter mask.
      WHITE: $FSLDIR/data/standard/tissuepriors/2mm/avg152T1_white_bin.nii.gz

      # Full path to a binarized Gray Matter mask.
      GRAY: $FSLDIR/data/standard/tissuepriors/2mm/avg152T1_gray_bin.nii.gz

      # Full path to a binarized CSF mask.
      CSF: $FSLDIR/data/standard/tissuepriors/2mm/avg152T1_csf_bin.nii.gz

registration_workflows: 
  functional_registration: 
    EPI_registration: 
      ANTs: 
        # EPI registration configuration - synonymous with T1_registration
        # parameters under anatomical registration above
        parameters:

functional_preproc: 
  truncation: 
    # First timepoint to include in analysis.
    # Default is 0 (beginning of timeseries).
    # First timepoint selection in the scan parameters in the data configuration file, if present, will over-ride this selection.
    # Note: the selection here applies to all scans of all participants.
    start_tr: 3

    # Last timepoint to include in analysis.
    # Default is None or End (end of timeseries).
    # Last timepoint selection in the scan parameters in the data configuration file, if present, will over-ride this selection.
    # Note: the selection here applies to all scans of all participants.
    stop_tr: End

  motion_estimates_and_correction: 
    motion_estimates: 
      # calculate motion statistics BEFORE slice-timing correction
      calculate_motion_first: On

  func_masking: 
    # using: ['AFNI', 'FSL', 'FSL_AFNI', 'Anatomical_Refined', 'Anatomical_Based']
    # this is a fork point
    using: [Anatomical_Refined]

 
nuisance_corrections: 
  2-nuisance_regression: 
    # Select which nuisance signal corrections to apply
    Regressors: 
      - Bandpass:
          bottom_frequency: 0.01
          top_frequency: 0.1
        CerebrospinalFluid:
          erode_mask: On
          extraction_resolution: 2
          summary: Mean
        Motion:
          include_delayed: On
          include_delayed_squared: On
          include_squared: On
        Name: Regressor-2
        PolyOrt:
          degree: 2
        aCompCor:
          extraction_resolution: 2
          summary:
            components: 5
            method: DetrendPC
          tissues:
          - WhiteMatter
          - CerebrospinalFluid

    # Standard Lateral Ventricles Binary Mask
    # used in CSF mask refinement for CSF signal-related regressions
    lateral_ventricles_mask: $FSLDIR/data/atlases/HarvardOxford/HarvardOxford-lateral-ventricles-thr25-2mm.nii.gz

timeseries_extraction: 
  run: Off

seed_based_correlation_analysis: 
  # SCA - Seed-Based Correlation Analysis
  # For each extracted ROI Average time series, CPAC will generate a whole-brain correlation map.
  # It should be noted that for a given seed/ROI, SCA maps for ROI Average time series will be the same.
  run: Off

amplitude_low_frequency_fluctuation: 
  # ALFF & f/ALFF
  # Calculate Amplitude of Low Frequency Fluctuations (ALFF) and and fractional ALFF (f/ALFF) for all voxels.
  run: Off

regional_homogeneity: 
  # ReHo
  # Calculate Regional Homogeneity (ReHo) for all voxels.
  run: On

voxel_mirrored_homotopic_connectivity: 
  # VMHC
  # Calculate Voxel-mirrored Homotopic Connectivity (VMHC) for all voxels.
  run: Off

  symmetric_registration: 
    # Included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
    # It is not necessary to change this path unless you intend to use a non-standard symmetric template.
    T1w_brain_template_symmetric: $FSLDIR/data/standard/MNI152_T1_${resolution_for_anat}_brain_symmetric.nii.gz

    # A reference symmetric brain template for resampling
    T1w_brain_template_symmetric_for_resample: $FSLDIR/data/standard/MNI152_T1_1mm_brain_symmetric.nii.gz

    # Included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
    # It is not necessary to change this path unless you intend to use a non-standard symmetric template.
    T1w_template_symmetric: $FSLDIR/data/standard/MNI152_T1_${resolution_for_anat}_symmetric.nii.gz

    # A reference symmetric skull template for resampling
    T1w_template_symmetric_for_resample: $FSLDIR/data/standard/MNI152_T1_1mm_symmetric.nii.gz

    # Included as part of the 'Image Resource Files' package available on the Install page of the User Guide.
    # It is not necessary to change this path unless you intend to use a non-standard symmetric template.
    dilated_symmetric_brain_mask: $FSLDIR/data/standard/MNI152_T1_${resolution_for_anat}_brain_mask_symmetric_dil.nii.gz

    # A reference symmetric brain mask template for resampling
    dilated_symmetric_brain_mask_for_resample: $FSLDIR/data/standard/MNI152_T1_1mm_brain_mask_symmetric_dil.nii.gz

network_centrality: 
  # Calculate Degree, Eigenvector Centrality, or Functional Connectivity Density.
  run: Off

# PACKAGE INTEGRATIONS
# --------------------
PyPEER: 
  # Template-space eye mask
  eye_mask_path: $FSLDIR/data/standard/MNI152_T1_${func_resolution}_eye_mask.nii.gz

```

### Run command

`docker run --user 1136:1054 --security-opt=apparmor:unconfined -i --rm -v /data3/autism_center/wave1/QC/cpac_1.8.3:/scratch -v /data3/autism_center/wave1/QC/cpac_1.8.3:/outputs -v /data3/autism_center/wave1/QC/cpac_1.8.3/config:/config -v /data3/autism_center/wave1/BIDS:/bids_dataset fcpindi/c-pac:release-v1.8.3 /bids_dataset /outputs participant --pipeline_file /config/pipeline_config_cpac_1.8.3.yml --save_working_dir --save_working_dir --tracking_opt-out --n_cpus 25 --mem_gb 20 --participant_label 30002`

### Expected behavior

The CPAC run would crash and would generate a crash file with the following error. \

```
Node inputs:

function_str = def get_idx(in_files, stop_idx=None, start_idx=None):
    """
    Method to get the first and the last slice for
    the functional run. It verifies the user specified
    first and last slice. If the values are not valid, it
    calculates and returns the very first and the last slice

    Parameters
    ----------
    in_file : string (nifti file)
       Path to input functional run

    stop_idx : int
        Last volume to be considered, specified by user
        in the configuration file

    stop_idx : int
        First volume to be considered, specified by user
        in the configuration file

    Returns
    -------
    stop_idx :  int
        Value of first slice to consider for the functional run

    start_idx : int
        Value of last slice to consider for the functional run

    """

    # Import packages
    from nibabel import load

    # Init variables
    img = load(in_files)
    hdr = img.get_header()
    shape = hdr.get_data_shape()

    # Check to make sure the input file is 4-dimensional
    if len(shape) != 4:
        raise TypeError('Input nifti file: %s is not a 4D file' % in_files)
    # Grab the number of volumes
    nvols = int(hdr.get_data_shape()[3])

    if (start_idx == None) or (int(start_idx) < 0) or (
        int(start_idx) > (nvols - 1)):
        startidx = 0
    else:
        startidx = int(start_idx)

    if (stop_idx == None) or (int(stop_idx) > (nvols - 1)):
        stopidx = nvols - 1
    else:
        stopidx = int(stop_idx)

    return stopidx, startidx

in_files = <undefined>
start_idx = 3
stop_idx = End

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 351, in run
    return super().run(updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)
  File "<string>", line 51, in get_idx
ValueError: invalid literal for int() with base 10: 'End'
```

### Acceptance criteria

The user should be able to run the CPAC pipeline to completion without any errors when they assign End to stop_tr in the pipeline config file.

### Screenshots

_No response_

### C-PAC version

v1.8.3

### Container platform

Docker

### Docker and/or Singularity version(s)

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tergeorge**
## Fixes

Fixes #1766  by @tergeorge 

## Description
This PR would make it possible for the user to assign "End" or "None" as the stop_idx value for time series extraction. 

## Technical details
Added the following test condition to func_preproc.py
```
   
 if (stop_idx in [None, "End"]) or (int(stop_idx) > (nvols - 1)):
        stopidx = nvols - 1
    else:
        stopidx = int(stop_idx)

    return stopidx, startidx

```
## Tests
To test this PR, do the following:
1. Create a pipeline config file with functional_preproc -> truncation -> stop_tr as End
2. Run CPAC with the pipeline config file updated as instructed in step 1.

The pipeline should run to completion without any errors.
## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Review by shnizzedy — APPROVED** [review]
Looks great to me!

My only suggestions would be

1. to update https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L752 in the schema to 
```Python
            'stop_tr': Maybe(Any(int, All(Capitalize, 'End')))
```
so the validator will change any casing of 'end' to 'End' (we'd also have to add `Capitalize` to [the `from voluptuous import`s](https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L23-L24)) so that option won't be case-sensitive for user-input but will always be in the casing we're checking for here https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/func_preproc/func_preproc.py#L577

2. to add a bullet about the fix to the CHANGELOG

but I think both of those things are just nice-to-haves, not strictly necessary

**Comment by shnizzedy** [comment]
@tergeorge I think all the merge conflicts here are just the version number and there's only one real commit here (not counting the CI version update commit), so instead of doing a conflict resolution, it'd probably be easier to (locally) do something like

```BASH
git fetch origin  # update local from GitHub
git checkout origin/develop  # checkout head of branch we're targeting
git branch -D fix_stop_idxEND  # delete current local name for this PR
git checkout -b fix_stop_idxEND  # recreate local name for this PR
git cherry-pick 201699b  # append the commit to this branch
git push origin fix_stop_idxEND -f  # force-push this updated branch to GitHub 
```

**Comment by tergeorge** [comment]
I didn't understand what you mean't by adding Capitalize over [here](https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L23-L24). Do you mean we import `Capitalize`?

**Comment by shnizzedy** [comment]
> I didn't understand what you mean't by adding Capitalize over [here](https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L23-L24). Do you mean we import `Capitalize`?

Sorry, yeah, I just mean if we do 
```Python
            'stop_tr': Maybe(Any(int, All(Capitalize, 'End')))
```
we need `from voluptuous import Capitalize` and that we could just add `Capitalize` to the objects imported in this line https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L23-L24

**Comment by tergeorge** [comment]
> > I didn't understand what you mean't by adding Capitalize over [here](https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L23-L24). Do you mean we import `Capitalize`?
> 
> Sorry, yeah, I just mean if we do
> 
> ```python
>             'stop_tr': Maybe(Any(int, All(Capitalize, 'End')))
> ```
> 
> we need `from voluptuous import Capitalize` and that we could just add `Capitalize` to the objects imported in this line
> 
> https://github.com/FCP-INDI/C-PAC/blob/e0063cdd637f1c7634341a5de114a2eba259f7af/CPAC/pipeline/schema.py#L23-L24

Got it! Thanks!

**Pull request merged**
