### PR TITLE
✨ Add commandline flags for scan inclusion

### LINKED ISSUE #1566: 🐛"No module named bids_utils" error
### Describe the bug

When running on the server, this error appeared. Can get around this error by adding:
-v $PATH_TO_CPAC/dev/docker_data/bids_utils.py:/code/bids_utils.py to the docker run command. 

### To reproduce

Run C-PAC in server within a develop branch. 

### Expected behavior

Should not be receiving that error 

### Acceptance criteria

Error will not appear when starting a CPAC run in (Lisa) server 

### Screenshots

Screen Shot 2021-09-16 at 11 19 29 AM

### C-PAC version

_No response_

### Container platform

_No response_

### Docker and/or Singularity version(s)

_No response_

### Additional context

_No response_

### LINKED ISSUE #1606: ✨ CLI flags for scan inclusion
### Related problem

There is no easy way to tell CPAC to only run one type of T1w or BOLD data from the command line. We can do it through the data config generator, but not through the CLI.

### Proposed feature

Similar to the `--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]` flag, it would be nice to have something like:

- `--T1w_label`
- `--bold_label`

### Acceptance criteria

- [x] `--T1w_label acq-VNavNorm` for an input file such as
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-CBIC/sub-NDARAA504CRN/anat/sub-NDARAA504CRN_acq-VNavNorm_T1w.nii.gz`
- [x] `--bold_label task-rest_run-1` for
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAC462DZH/func/sub-NDARAC462DZH_task-rest_run-1_bold.nii.gz`
- [x] `--bold_label [task-rest_run-1 task-rest_run-2]` to include both
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAC462DZH/func/sub-NDARAC462DZH_task-rest_run-1_bold.nii.gz` and
  - `s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAC462DZH/func/sub-NDARAC462DZH_task-rest_run-2_bold.nii.gz`

### Alternatives

_No response_

### Additional context

Caveats/points of possible complication:

- C-PAC currently combines `task-*`, `acq-*`, and `run-*` into one "scan label". For example, `task-rest_run-01` is listed as the scan name in the data configuration. This prevents the flexibility needed for full BIDS compliance - for example, it should be that selecting `--bold_label task-rest` should select both `task-rest_run-01` and `task-rest_run-02`, but at this moment, it would not. At the least, with the way the input data parser is structured.
  - This is worth changing, but may be much out of the scope of this issue and should probably be its own.
- C-PAC only runs one T1w per participant-session at a time, at this time. So providing a list of T1w labels may not be feasible right now. It may be worth making it so that C-PAC will run a pipeline for each T1w scan specified, though this feature may not be widely used/needed. Low priority.
- Currently, C-PAC will choose the first T1w it finds. This is not ideal if there are many different T1w's in the directory, and if this, by chance, leads the data configuration to have something like `acq-VNavNorm_T1w` for one participant and `acq-HCP_T1w` for another participant from the same site directory, for one run. Providing a `--T1w_label LABEL` would iron out this inconsistency (and possibly lead to participants being dropped if the user selects `acq-VNavNorm` for example, and some participants only have `acq-HCP`).
  - However, if the user does not provide this flag, we should still have something in place to look out for this inconsistency. It may be worth having a pre-defined set of priority (example, `VNavNorm` tends to be the T1w of choice), or maybe searching the `dataset_description.json` for any notes.
  - Either way, again this is beyond the scope and should be its own issue.

### PR DESCRIPTION
**Pull request by shnizzedy**
## Fixes

Fixes #1606 by @sgiavasis 
Fixes #1566 by @amygutierrez 

## Description

* Adds two new commandline arguments: https://github.com/FCP-INDI/C-PAC/blob/72aafe9d2341f3e24e52e9133bc1cb88f9043e1b/dev/docker_data/run.py#L248-L279

### for developers / packaging
* Deduplicates `bids_utils.py`, removing the copy in [`dev/docker_data/`](https://github.com/FCP-INDI/C-PAC/blob/bda63c569402d75a7f12526ced4439a989897421/dev/docker_data/bids_utils.py) in favor of the one in [`CPAC/utils/`](https://github.com/FCP-INDI/C-PAC/blob/72aafe9d2341f3e24e52e9133bc1cb88f9043e1b/CPAC/utils/bids_utils.py) and updating the relevant import: https://github.com/FCP-INDI/C-PAC/blob/72aafe9d2341f3e24e52e9133bc1cb88f9043e1b/dev/docker_data/run.py#L17-L24

## Technical details

In [`run.py`](https://github.com/FCP-INDI/C-PAC/blob/72aafe9d2341f3e24e52e9133bc1cb88f9043e1b/dev/docker_data/run.py), I moved the main script from top-level into [a function](https://github.com/FCP-INDI/C-PAC/blob/72aafe9d2341f3e24e52e9133bc1cb88f9043e1b/dev/docker_data/run.py#L96) [called when `__name__ == '__main__'`](https://github.com/FCP-INDI/C-PAC/blob/72aafe9d2341f3e24e52e9133bc1cb88f9043e1b/dev/docker_data/run.py#L736-L737), and the git diff for that is not as clean as I'd like it to be ― it doesn't see that the whole top-level script is nested one level, so the line-by-line from [that commit](https://github.com/FCP-INDI/C-PAC/commit/7a99aa57de9eab8b3f134e1a0dbf29db1e8c0fa8) is confusing.
* Several functions were defined in both `bids_utils.py` and `run.py`. I merged the ones I noticed into `bids_utils` and imported them from `bids_utils` into `run` (for a single-source-of-truth)
* > C-PAC currently combines task-*, acq-*, and run-* into one "scan label". For example, task-rest_run-01 is listed as the scan name in the data configuration. This prevents the flexibility needed for full BIDS compliance - for example, it should be that selecting --bold_label task-rest should select both task-rest_run-01 and task-rest_run-02, but at this moment, it would not. At the least, with the way the input data parser is structured.
  > ― https://github.com/FCP-INDI/C-PAC/issues/1606#issue-1036468245
  The way this PR is written, sequence matters, i.e. `task-rest_run-01` ≠ `run-01_task-rest`, and full tags are needed, so `task-rest`, `run-01`, and `task-rest_run-01` would all match `task-rest_run-01`, but `rest`, `run-01`, `run-`, `task-r`, and `run-01_task-rest` would all not match.

  If a user provides a partial match for a single entity, the error will suggest the match like
  > ```Python
  > LookupError: No match found for provided entity "run-" in
  > - task-rest_run-01
  > - task-rest_run-02
  > Perhaps you meant one of these?
  > - run-01
  > - run-02
  > ```
  
  It might be worth adding globbing, but it might be low-usage enough that it's good enough to just list all the would-be-matches (e.g. `--bold_label [task-rest_run-01 task-rest_run-02]` instead of `--bold_label task-rest_run-0*` (the `*` one won't work as written)
* > C-PAC only runs one T1w per participant-session at a time, at this time. So providing a list of T1w labels may not be feasible right now. It may be worth making it so that C-PAC will run a pipeline for each T1w scan specified, though this feature may not be widely used/needed. Low priority.
  > ― https://github.com/FCP-INDI/C-PAC/issues/1606#issue-1036468245
  This is still the case. I think using more than one T1w would involve some refactoring, so in a `sub_list`, the key `anat` still takes a string value (you can now provide a list in a data config, but it will use the first item unless you use the new `--T1w_label` flag)
* > Currently, C-PAC will choose the first T1w it finds.
  > ― https://github.com/FCP-INDI/C-PAC/issues/1606#issue-1036468245
  This is still the case here if a user does not provide `--T1w_label`
* Because this PR merges `/dev/docker_data/bids_utils.py` into `/CPAC/utils/bids_utils.py` and #1608 makes improvements in the former file, I'd like to wait until #1608 is merged into develop, then merge those changes into this branch before merging these changes.

## Tests

* Try any of the listed acceptance criteria in #1606
* Doctests
  * in `bids_utils.py`: https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/bids_utils.py#L106-L109 https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/bids_utils.py#L135-L152 https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/bids_utils.py#L371-L377 https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/bids_utils.py#L933-L936 https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/bids_utils.py#L1000-L1010
  * in `utils.py`: https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/utils.py#L113-L118
* Pytest tests in [`CPAC/utils/tests/test_bids_utils.py`](https://github.com/FCP-INDI/C-PAC/blob/510b478543e10738e2d2e03cc42494c6d28bbaac/CPAC/utils/tests/test_bids_utils.py) 

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I updated the changelog.
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
If no scans are found for a participant, it raises an error like:

```Python
LookupError: No match found for provided entity "acq-VNavNorm" in
- s3://fcp-indi/data/Projects/HBN/MRI/Site-RU/sub-NDARAA306NT2/anat/sub-NDARAA306NT2_acq-HCP_T1w.nii.gz
```

Is that good, or should it return an empty list or `None`?

**Comment by shnizzedy** [comment]
> re: the T2 parsing and the scan labels, it's rare that there will be more than one T2 acquired, so we need to be able to link the same T2 to multiple T1s. however, there may be cases (like HBN) where there IS a T2 for each T1 acq.

**Comment by shnizzedy** [comment]
How's this strategy for handling `T2w`s with a `--T1w_label`?

<table>
<tr><td colspan="2" bgcolor="black" /><th>mutiple <code>T2w</code>s</th><th>single <code>T2w</code></th></tr>
<tr><th rowspan="2"><code>--T1w_label</code></th><th>matches</th><td>filter <code>T2w</code></td><td rowspan="3">grab only <code>T2w</code></td></tr>
<tr><th>does not match</th><td rowspan="2">grab first <code>T2w</code> found</td></tr>
<tr><th colspan="2">no <code>--T1w_label</code></th>
</table>

**Comment by sgiavasis** [comment]
> How's this strategy for handling `T2w`s with a `--T1w_label`?
> 
> mutiple `T2w`s	single `T2w`
> `--T1w_label`	matches	filter `T2w`	grab only `T2w`
> does not match	grab first `T2w` found
> no `--T1w_label`

Looks great!

**Review by sgiavasis — APPROVED** [review]

**Pull request merged**
