### PR TITLE
Add ruff and pre-commit (linting + formatting)

### PR DESCRIPTION
**Pull request by nx10**
## Description

This PR adds [pre-commit](https://pre-commit.com/) hooks for Ruff and various smaller code quality assurance tools.

It will run on a per-file basis, but pre-commit run --all-files should be run to format the entire repository once before/directly after this is merged.

This PR supersedes https://github.com/FCP-INDI/C-PAC/pull/1882

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by nx10** [comment]
@shnizzedy noted that we likely want to discuss the selection of pre-commit hooks and ruff settings here before we move on with this. (@sgiavasis @gkiar @e-kenneally @birajstha @ReinderVosDeWael)

**Comment by nx10** [comment]
We can use the contributing guidelines Jon wrote [here](https://github.com/FCP-INDI/C-PAC/pull/2046/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055)

**Comment by ReinderVosDeWael** [comment]
My suggestion would be to start small with only a core set of checks, and then slowly expanding the number of checks with time, rather than trying to do it all in one go. Also see if it is possible to only run Ruff on modified files. In a codebase as large as C-PAC trying to do it all in one go will be a herculean task that is bound to cause a bunch of fun merge conflicts for anyone who simultaneously works on anything else. Instead, you can diffuse the responsibility over time by having each developer be responsible for porting the files that they work on. 

I think a good place to start for specific checks is our [template repository](https://github.com/childmindresearch/template-python-repository/blob/main/pyproject.toml#L63). In repos where I'm the only dev I tend to go much stricter with only specific exclusions (e.g. [ctk-api](https://github.com/childmindresearch/ctk-api/blob/main/pyproject.toml#L83), but this may not be feasible in a code-base this large. 

As for pre-commit hooks: mypy.

**Review by shnizzedy — COMMENTED** [review]
> We can use the contributing guidelines Jon wrote [here](https://github.com/FCP-INDI/C-PAC/pull/2046/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055)

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894384217

[Here's that Markdown rendered](https://github.com/FCP-INDI/C-PAC/blob/2156b59c1b439162dc2a5cda792f74d49b855144/CONTRIBUTING.md#pre-commit)

---

> My suggestion would be to start small with only a core set of checks, and then slowly expanding the number of checks with time, rather than trying to do it all in one go.

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894389067

<a href="https://knowyourmeme.com/memes/spider-man-pointing-at-spider-man">agreed</a> Agreed. Some of the conversation was on Slack / over video, but that's what I'm talking about [here](https://github.com/FCP-INDI/C-PAC/pull/1882#issuecomment-1850327342) when I say "first iteration"

> Also see if it is possible to only run Ruff on modified files. In a codebase as large as C-PAC trying to do it all in one go will be a herculean task that is bound to cause a bunch of fun merge conflicts for anyone who simultaneously works on anything else. Instead, you can diffuse the responsibility over time by having each developer be responsible for porting the files that they work on.

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894389067

That was my instinct as well, but some of the files are so monstrous that we'd either have a two-step process for PRs on unlinted files (1. lint 2. make real changes) or the real changes will be drowned out by linting in the diff. We held #1882 until the beginning of the subsequent release cycle with the intent to get the (first round of) linting over with in one big go before most of the development and testing.

That said, `pre-commit` will run `ruff` on only changed files, so if we just set up the pre-commit config without doing a big Ruff run, we could start doing that two-step process. Another couple advantages to that strategy are:

* it will become obvious in the code what hasn't changed for a long time
* we can include more style rules in the first iteration without being too heavy-handed than we could if we're going to do a big linting

> I think a good place to start for specific checks is our [template repository](https://github.com/childmindresearch/template-python-repository/blob/main/pyproject.toml#L63).

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894389067

agreed</a> Agreed again. I think we could probably add all of those hooks in this PR without going out of scope (but probably keep #2046 separate)

> In repos where I'm the only dev I tend to go much stricter with only specific exclusions (e.g. [ctk-api](https://github.com/childmindresearch/ctk-api/blob/main/pyproject.toml#L83), but this may not be feasible in a code-base this large.

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894389067

I think that's something to work up to here, but I could be convinced otherwise

> As for pre-commit hooks: mypy.

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894389067

agreed</a> +1

**Comment by nx10** [comment]
> > Also see if it is possible to only run Ruff on modified files. In a codebase as large as C-PAC trying to do it all in one go will be a herculean task that is bound to cause a bunch of fun merge conflicts for anyone who simultaneously works on anything else. Instead, you can diffuse the responsibility over time by having each developer be responsible for porting the files that they work on.
> 
> ― [#2048 (comment)](https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1894389067)
> 
> That was my instinct as well, but some of the files are so monstrous that we'd either have a two-step process for PRs on unlinted files (1. lint 2. make real changes) or the real changes will be drowned out by linting in the diff. We held #1882 until the beginning of the subsequent release cycle with the intent to get the (first round of) linting over with in one big go before most of the development and testing.
> 
> That said, `pre-commit` will run `ruff` on only changed files, so if we just set up the pre-commit config without doing a big Ruff run, we could start doing that two-step process. Another couple advantages to that strategy are:
> 
> * it will become obvious in the code what hasn't changed for a long time
> * we can include more style rules in the first iteration without being too heavy-handed than we could if we're going to do a big linting

I agree with Jon here: With CPACs massive files in mind I think one run formatting everything would be much more manageable than having random PRs drowning in reformatting and a huge number of potential merge conflicts (many PRs in CPAC stay open for months while a lot of changes happen on other fronts)

The additional lints Jon chose seem sensible to me, especially e.g. the Numpy ones, which would auto-fix e.g. https://github.com/FCP-INDI/C-PAC/issues/1992 .

**Comment by nx10** [comment]
Oh and Re: mypy

I think that would deserve its own PR after this one - potentially one that uses one of the type inference tools to auto annotate wherever possible

**Comment by shnizzedy** [comment]
If we do want to just `ruff` changed sections instead of changed files on commit, we could replace the `ruff` hook with something like

```YAML
- repo: https://github.com/akaihola/darker
  rev: 1.7.2
  hooks:
    - id: darker
      args:
        - --lint "ruff check --fix"
        - --lint "ruff format"
      additional_dependencies:
        - ruff==0.1.13
```

(and do the same with mypy or whatever other linters), but I lean toward linting the whole files when committing, especially if we do the big linting once.

**Comment by shnizzedy** [comment]
> One thing I am wondering about is if the yaml formatter will cause an endless loop with the config update bot

― https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1896245716

I think that bot should not enter a loop ― it should skip if its own commit is most recent. But if we merge https://github.com/FCP-INDI/C-PAC/pull/2046 before this one, then that bot'll be gone and it'll all just be in pre-commit

**Comment by shnizzedy** [comment]
> > One thing I am wondering about is if the yaml formatter will cause an endless loop with the config update bot
> 
> ― [#2048 (comment)](https://github.com/FCP-INDI/C-PAC/pull/2048#issuecomment-1896245716)
> 
> I think that bot should not enter a loop ― it should skip if its own commit is most recent. But if we merge #2046 before this one, then that bot'll be gone and it'll all just be in pre-commit

Now that #2046 and #2056 are merged, the config update bot is gone. Is there anything else we need to wait for before this one becomes ready-for-review?

**Comment by nx10** [comment]
It's good to go from my side, someone just needs to commit with @ChildMindInstituteCNL after running
```sh
pre-commit run --all-files
```

**Comment by shnizzedy** [comment]
> It's good to go from my side, someone just needs to commit with @ChildMindInstituteCNL after running
> 
> ```shell
> ruff . --fix --unsafe-fixes
> pre-commit run --all-files
> ```

Awesome. I just rebased this branch onto the updated `develop` and I'll have @ChildMindInstituteCNL commit the big run as a PR into this branch for us to review separately from these changes

**Comment by nx10** [comment]
Now that the PRs are merged we should probably bump up ruff to the newest version (0.3.2). They did not break the API but some config fields got changed / deprecated.

**Pull request merged**
