### PR TITLE
[ENH] Fetch NDMG templates from Neuroparc

### PR DESCRIPTION
**Pull request by anibalsolon**

### CODE REVIEW

**Comment by sgiavasis** [comment]
😍 didn't know you were working on this, thank you!

**Comment by anibalsolon** [comment]
@sgiavasis I figure you asked us and no one answered you :laughing:

**Comment by sgiavasis** [comment]
The ndmg-neuroparc was originally branched off of Master? i.e. it is runnable on its own?

**Comment by anibalsolon** [comment]
Yes, I changed the branch afterwards. I guess merging master into 1.4.2/final will cleanup this PR, one moment.

**Pull request closed without merging**
