### PR TITLE
⬆️ Upgrade Nipype to v1.5.1 (from 1.1.2)

### LINKED ISSUE #1375: ✨ Upgrade to Nipype 1.5.1
**Related problem**
It's time to upgrade C-PAC's Nipype dependency.

**Proposed feature**
Upgrade C-PAC (and it's containers) to [Nipype 1.5.1](https://github.com/nipy/nipype/releases/tag/1.5.1).

**Additional context**
Let's re-test these once this upgrade is completed in `develop`:
- https://github.com/FCP-INDI/C-PAC/issues/1301
- https://github.com/FCP-INDI/C-PAC/issues/1338

### PR DESCRIPTION
**Pull request by shnizzedy**
## Fixes

Fixes #1375 by @sgiavasis 

## Description

* Upgrades Nipype from 1.1.2 to 1.5.1
    The biggest change here is "[substantially expand functionality of 3dROIstats interface](https://github.com/nipy/nipype/commit/05c056c5285f0cb9a76d1bf967278231fe4ff03e)". For this change:
    * `stats` becomes `out_file`
    * `mask` becomes `mask_file`
    * extension changes from `.csv` to `.1D`
    * reverts #1328. Where having the header commented in a CSV was causing a `has {x-1} time points, but dataset has {x} values` error, having the header uncommented in a 1D file causes an error where AFNI expects every cell in the 1D file to be a number.
* Upgrades Python from 3.6.3 to 3.9.0
* [Simplifies the autotagging](https://github.com/FCP-INDI/C-PAC/commit/f05330cab5ed0332f38a5ce31f2c7eb1f3b4e062)
    #1360 doesn't work as well as I had hoped, so I think it's better to just have `semver.dev` in the 22 files that include the version than have to deal with a bunch of rebasing and/or merging for `semver.hash.dev` version tags in 22 files each time we merge branches.
    **You can `git cherry-pick` the latest commit of the branch [`devops/simpler-dev-version-tags`](https://github.com/FCP-INDI/C-PAC/tree/devops/simpler-dev-version-tags) to get this simplified CI version updating in any branch.**

## Technical details

* [Updgrades CircleCI machine](https://github.com/FCP-INDI/C-PAC/commit/d1be7c532c3053a0b1acf270c3980c6410cb7296) to [one with Python 3.9 support](https://circleci.com/docs/2.0/configuration-reference/#available-machine-images)
    * [Upgrades libssl from 1.0.0 to 1.1](https://github.com/FCP-INDI/C-PAC/commit/81bdc3db7a0195bdf012b31979581d06e3962ee7) for that machine

## Tests

Currently running 
* the default pipeline on s3://fcp-indi/data/Projects/ADHD200/RawDataBIDS with `--participant_ndx 4` (https://github.com/FCP-INDI/cpac_run_logs/issues/6)
* `fmriprep-options` with [this data config](https://raw.githubusercontent.com/FCP-INDI/C-PAC/upgrade/nipype-1.5.1/CPAC/resources/configs/test_configs/data-test_4-projects_5-subjects.yml)

The crashfiles generated so far involve:
* #1260 still happening
* `afni_centrality`
* `sca`

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
See https://github.com/FCP-INDI/cpac_run_logs/issues/6 for results of a single-subject test run.

**Comment by shnizzedy** [comment]
I've also got a run (still going) with [`data-test_4-projects_5-subjects.yml`](https://raw.githubusercontent.com/FCP-INDI/C-PAC/master/CPAC/resources/configs/test_configs/data-test_4-projects_5-subjects.yml) data config so I can check correlations with the outputs I got for `fmriprep-options` for v1.7.2. So far that one's had a`slice_timing.b2` occur 3 times and no other crash files.

```Python
File: /media/ebs/upgrade_nipype/2020-11-02_default-data_fmriprep-options_upgrade-nipype/crash/crash-20201104-090240-UID1000-slice_timing.b2-ed8b6b17-35bd-4e93-97dc-a9c799272685.pklz
Node: resting_preproc_A00028185_NFB3.func_slice_timing_correction_0.slice_timing
Working directory: /media/ebs/upgrade_nipype/2020-11-02_default-data_fmriprep-options_upgrade-nipype/working/resting_preproc_A00028185_NFB3/func_slice_timing_correction_0/_scan_MASK/slice_timing


Node inputs:

args = <undefined>
environ = {}
ignore = <undefined>
in_file = /media/ebs/upgrade_nipype/2020-11-02_default-data_fmriprep-options_upgrade-nipype/working/resting_preproc_A00028185_NFB3/func_slice_timing_correction_0/_scan_MASK/slice_timing/sub-A00028185_ses-NFB3_task-MASK_bold_calc.nii.gz
interp = <undefined>
num_threads = 1
out_file = <undefined>
outputtype = NIFTI_GZ
rlt = <undefined>
rltplus = <undefined>
slice_encoding_direction = k
slice_timing = <undefined>
tpattern = @/media/ebs/upgrade_nipype/2020-11-02_default-data_fmriprep-options_upgrade-nipype/working/resting_preproc_A00028185_NFB3/_scan_MASK/scan_params_0/tpattern.txt
tr = 2.0s
tslice = <undefined>
tzero = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/linear.py", line 46, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/afni/base.py", line 125, in _run_interface
    runtime, correct_return_codes
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 814, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 745, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
3dTshift -prefix sub-A00028185_ses-NFB3_task-MASK_bold_calc_tshift.nii.gz -tpattern @/media/ebs/upgrade_nipype/2020-11-02_default-data_fmriprep-options_upgrade-nipype/working/resting_preproc_A00028185_NFB3/_scan_MASK/scan_params_0/tpattern.txt -TR 2.0s /media/ebs/upgrade_nipype/2020-11-02_default-data_fmriprep-options_upgrade-nipype/working/resting_preproc_A00028185_NFB3/func_slice_timing_correction_0/_scan_MASK/slice_timing/sub-A00028185_ses-NFB3_task-MASK_bold_calc.nii.gz
Standard output:

Standard error:
++ 3dTshift: AFNI version=AFNI_20.3.01 (Oct 19 2020) [64-bit]
** FATAL ERROR: -ignore value 0 is too large
** Program compile date = Oct 19 2020
Return code: 1
```

**Comment by shnizzedy** [comment]
Do we want to wait for any of these crashes to be handed or resolved before we merge into develop? Or merge to develop and open issues? Some of each?

- [ ] `IndexError: cannot do a non-empty take from an empty axes.`
- [ ] `****The number of timepoints (251) is smaller than the number of ROIs to run (392) - therefore the GLM is underspecified and can't run.****` (this one's possibly just a mismatch between data and pipeline config)
- [ ] `Fatal Signal 11 (SIGSEGV) received` `3dECM main` / `** ERROR: Memory budget (975.730408 MB) exceeded, consider using ahigher correlation or lower sparsity threshold`
- [x] https://github.com/FCP-INDI/C-PAC/issues/1260 is already an issue

**Review by sgiavasis — APPROVED** [review]

**Comment by sgiavasis** [comment]
Great work here @shnizzedy 🙏

**Pull request merged**
