### PR TITLE
🔧 Enforce forkability in Configuration

### PR DESCRIPTION
**Pull request by shnizzedy**
## Description

* When loading a Configuration, any value that can be set as either a boolean or a list of booleans is coerced to a list of booleans
* Updates conditionals that look for `bool(«something»['run'])` to look instead for `True in «something»['run']`
* Adds a few such conditionals:
   * https://github.com/FCP-INDI/C-PAC/blob/00418dd1a78cd45890db02c23ea4529cf571471c/CPAC/pipeline/cpac_pipeline.py#L946-L952
   * https://github.com/FCP-INDI/C-PAC/blob/00418dd1a78cd45890db02c23ea4529cf571471c/CPAC/pipeline/cpac_pipeline.py#L979-L981
   * https://github.com/FCP-INDI/C-PAC/blob/05dfb63cc1da8823e48d3ac049b6a895c8eca163/CPAC/pipeline/cpac_pipeline.py#L967-L969

I'm not sure if I caught them all (and please double-check the ones I added are the correct `['run']`s), but the pipeline config that I was trying to run is now running!

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop_v1.8_convergence` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
@sgiavasis @hahaai 

I made the changes I mentioned on Slack (https://github.com/FCP-INDI/C-PAC/pull/1433/commits/e3b29c657cd50c809d2f40ad16bcc85b0b5d9f9e and https://github.com/FCP-INDI/C-PAC/pull/1433/commits/07ba24ca56ac9fb641364d197fbac16ef3f6e1dc), but in making the second commit, I noticed this section looks like it's either missed a re-refactor or got messed up in a merge somewhere:

https://github.com/FCP-INDI/C-PAC/blob/06b8adc1483aa686dde32b1c27c7bf23f44573b9/CPAC/longitudinal_pipeline/longitudinal_workflow.py#L1053-L1072

I haven't made any changes there, so it shouldn't affect this merge, but `2-func_registration_to_template` isn't in the config anymore.

**Review by sgiavasis — APPROVED** [review]
Okay, fantastic. We're almost there.
I wanted to fix some ingress parsing before merging this in.

There is one thing I wanted to clarify actually - I realized it's a moot point to make the registrations and derivatives forkable, because the registrations lead to pipeline endpoints that don't impact the alternative (native-space endpoints), and because the derivatives are endpoints themselves.

In contrast, something like the preprocs should be forkable because On,Off would enable having the preprocessed data, and the raw data, both go into registration/nuisance/derivatives etc.

So those don't need to be lists, and we're probably better off removing the `if True in X` and just using a straight bool check like `if cfg.network_centrality['run']:`.

I'll actually merge this in because I'd like to get the container running now, and changing those bool checks are just a few lines and I can do it. But I wanted to let you know so everyone knows why it changed.

**Comment by sgiavasis** [comment]
Re: the longitudinal_workflow.py usage of the old pipeline config key - I've already fixed this in my local and will be pushing that soon.

**Comment by shnizzedy** [comment]
> So those don't need to be lists, and we're probably better off removing the `if True in X` and just using a straight bool check like `if cfg.network_centrality['run']:`.

The way the importer works, we'll have to update those keys in the schema from `forkable` to `bool` and update any affected pipeline configs accordingly. That way it'll complain if someone sets a non-forkable key to `[Off]`. Otherwise `[Off]` will evaluate as `True` for those conditionals which is definitely not what a user would want.

**Pull request merged**
