### PR TITLE
👷 Run unit tests in CI

### PR DESCRIPTION
**Pull request by shnizzedy**
## Description

Updates Circle CI configuration to run, for each variant 
* unit tests in Docker
* unit tests in Singularity
* report combined coverage from those runs

- [x] resolve or skip the 49 [consistently](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/486/workflows/289e64a0-9545-4828-a8a5-395b484154eb/jobs/2758) [failing](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/486/workflows/289e64a0-9545-4828-a8a5-395b484154eb/jobs/2759) unit tests
- [x] annotates test failures
- [x] removes remnants of the old GUI

## Screenshots

[workflow](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/1580/workflows/1c87af24-19ed-465a-be68-d0002f5ca60b)

### tests pass
"good job; 107 tests passed"

[coverage HTML](https://6201-4733263-gh.circle-artifacts.com/0/htmlcov/index.html)

### example failing test
["2 tests failed out of 105"](https://app.circleci.com/pipelines/github/shnizzedy/C-PAC/390/workflows/24704aa4-dde2-4a95-8770-84ac542d587d/jobs/1503)

## Future
- Report coverage ― _[codecov](https://codecov.io/)? [coveralls](coveralls.io)? Both? Neither?_
- Update skipped tests
- Include passing doctests in documentation (some already are included, and some skipped tests are currently included, e.g. 
[create_sca
)](https://fcp-indi.github.io/docs/latest/developer/workflows/sca.html#CPAC.sca.create_sca)
- Add testing guidlines to developer docs 
[screenshot of https://fcp-indi.github.io/docs/latest/developer/testing](https://fcp-indi.github.io/docs/latest/developer/testing)
- Add linting to CI
- Optimize CI flow (so, for example, we don't have to wait over an hour for each build, and another 30 minutes+ to reload the images when we combine coverage)
- Build up some automated regression testing (e.g., on PR) after #1455

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update
  index.md`).
- [x] My pull request targets the `develop` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [ ] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no
  visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by sgiavasis** [comment]
_WHEE!_

**Comment by shnizzedy** [comment]
For posterity, here's the original description of this PR:

> ## Description
> 
> Updates Circle CI configuration to run 
> * unit tests in Docker
> * unit tests in Singularity
> * one random subject through one random preconfig in Docker
> * one random subject through one random preconfig in Singularity
> * report combined coverage from those four runs
> 
> ### To do
> - [x] resolve or skip the 49 [consistently](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/486/workflows/289e64a0-9545-4828-a8a5-395b484154eb/jobs/2758) [failing](https://app.circleci.com/pipelines/github/FCP-INDI/C-PAC/486/workflows/289e64a0-9545-4828-a8a5-395b484154eb/jobs/2759) unit tests
> - [ ] see about some web-accessible images for testing (like [CPAC/resources/configs/test_configs/data-test_4-projects_5-subjects.yml](https://github.com/FCP-INDI/C-PAC/blob/develop/CPAC/resources/configs/test_configs/data-test_4-projects_5-subjects.yml)) for
>    - [ ] rodent
>    - [ ] nhps
>        - [ ] macaques
>        - [ ] monkeys
> - [ ] maybe limit the full random runs to PRs and just do unit tests on pushes? Building already takes an hour, and a run can add several more
> 
> ## Screenshots
> 
> screenshot of workflow on CircleCI

**Comment by sgiavasis** [comment]
@shnizzedy Amazing work, holy cow 👏

**Comment by anibalsolon** [comment]
```
* deletes the /GUI folder *
* souls wailing, leaving GitHub servers *
```

**Comment by shnizzedy** [comment]
soul leaving server

**Pull request merged**
