### PR TITLE
🔒️ Add `sha384sum` checks for 1.8.6 installation steps

### PR DESCRIPTION
**Pull request by shnizzedy**
## Related to

Related to #1920 by @nx10
Related to #1916 by @shnizzedy

## Description

- Replaces https://github.com/FCP-INDI/C-PAC/blob/c9bc551a1f2a6f425681484cdfd46f1b74c0416f/.github/Dockerfiles/Ubuntu.Python3.10-bionic-non-free.Dockerfile#L127 with https://github.com/FCP-INDI/C-PAC/blob/2e51cd994c56f16710b370ee7f2e89b8302e8a13/.github/Dockerfiles/Ubuntu.Python3.10-bionic-non-free.Dockerfile#L127 https://github.com/FCP-INDI/C-PAC/blob/2e51cd994c56f16710b370ee7f2e89b8302e8a13/.github/Dockerfiles/Ubuntu.Python3.10-bionic-non-free.Dockerfile#L130 , including a copy of the current https://bootstrap.pypa.io/get-pip.py in [`dev/docker_data/get-pip_23.0.1.py`](https://github.com/FCP-INDI/C-PAC/blob/2e51cd994c56f16710b370ee7f2e89b8302e8a13/dev/docker_data/get-pip_23.0.1.py)
- Replaces https://github.com/FCP-INDI/C-PAC/blob/c9bc551a1f2a6f425681484cdfd46f1b74c0416f/.github/Dockerfiles/Ubuntu.Python3.10-bionic-non-free.Dockerfile#L131 with https://github.com/FCP-INDI/C-PAC/blob/4b8c780276d24e2090574402aa2c7c4987e58141/.github/Dockerfiles/Ubuntu.Python3.10-bionic-non-free.Dockerfile#L128-L129 https://github.com/FCP-INDI/C-PAC/blob/4b8c780276d24e2090574402aa2c7c4987e58141/.github/Dockerfiles/Ubuntu.Python3.10-bionic-non-free.Dockerfile#L134-L135 , including a signed source list in [`dev/docker_data/github_git-lfs.list`](https://github.com/FCP-INDI/C-PAC/blob/2e51cd994c56f16710b370ee7f2e89b8302e8a13/dev/docker_data/github_git-lfs.list)
- For each remaining `curl` command in the current set of standard and lite Dockerfiles (excluding the ABCD-HCP and fMRIPrep-LTS variants), adds an `sha384sum --check` after downloading.

## Technical details

* Checksums were calculated with `sha384sum` and are stored in a [`dev/docker_data/checksum/`](https://github.com/FCP-INDI/C-PAC/tree/f582be466f52b9d39eb58a5281a08543985bbb64/dev/docker_data/checksum)`${stage}.sha384` file for each stage with `curl` steps in the Dockerfile.

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `upgrade/python` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [ ] I added tests for the changes I made (if applicable).
- [x] I updated the changelog.
- [ ] I added or updated documentation (if applicable).
- [ ] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by nx10** [comment]
Much better than before! But MD5 specifically is [very insecure](https://en.m.wikipedia.org/wiki/MD5#Security) (i.e. it's easy to generate files with the same sum) so we might want to go with something like sha256.

**Comment by shnizzedy** [comment]
Based on [this table Comparison of SHA functions](https://en.wikipedia.org/wiki/SHA-2#Comparison_of_SHA_functions)
, maybe sha384?

**Comment by nx10** [comment]
I think most package managers use Sha256 but anything ≥ that sounds good to me!

**Review by nx10 — APPROVED** [review]
Lgtm 🚀

**Pull request merged**
