### PR TITLE
🔧 Update RBC preconfig

### LINKED ISSUE #1642: 🔧 Make `ndmg` correlation matrices a configurable option
### Related problem

Currently, if `timeseries_extraction.run` is `On`, you get `desc-ndmg_correlations` whether you want them or not

### Proposed feature

Add a switch for `ndmg_correlations`

### Acceptance criteria

- [ ] `ndmg_correlations` is configurable

### Alternatives

_No response_

### Additional context

_No response_

### LINKED ISSUE #1702: 🐛 `convert_motionxfm2itk_188`: `c3d_affine_tool […] died with <Signals.SIGABRT: 6>`
### Describe the bug

```Python
Node: cpac_sub-colornest035_ses-1.convert_motionxfm2itk_188
Working directory: /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/convert_motionxfm2itk_188

Node inputs:

function_str = def run_c3d(reference_file, source_file, transform_file):

    import os
    import subprocess

    itk_transform = os.path.join(os.getcwd(), 'affine.txt')

    cmd = ['c3d_affine_tool', '-ref', reference_file, '-src',
            source_file, transform_file, '-fsl2ras', '-oitk', itk_transform]
    retcode = subprocess.check_output(cmd)

    return itk_transform

reference_file = <undefined>
source_file = <undefined>
transform_file = ['/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/oned_matrix_concat_86/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc.aff12.1D']

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 388, in run
    return super().run(updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1295, in _collate_results
    "Subnodes of node: %s failed:\n%s" % (self.name, "\n".join(msg))
Exception: Subnodes of node: convert_motionxfm2itk_188 failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)

  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/utility/wrappers.py", line 142, in _run_interface
    out = function_handle(**args)

  File "<string>", line 10, in run_c3d

  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

subprocess.CalledProcessError: Command '['c3d_affine_tool', '-ref', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/func_get_fmriprep_ref_83/ref_bold.nii.gz', '-src', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/func_get_fmriprep_ref_83/ref_bold.nii.gz', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/oned_matrix_concat_86/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc.aff12.1D', '-fsl2ras', '-oitk', '/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/convert_motionxfm2itk_188/mapflow/_convert_motionxfm2itk_1880/affine.txt']' died with <Signals.SIGABRT: 6>.
```

Running the command in a container:
```C
terminate called after throwing an instance of 'char const*'
```

### To reproduce

Run with

```YML
functional_preproc:
  motion_estimates_and_correction:
    motion_correction:
      using: [3dvolreg]
registration_workflows: 
  functional_registration:
    func_registration_to_template:
      apply_transform:
        using: single_step_resampling
```

### Expected behavior

`c3d_affine_tool` succeeds

### Acceptance criteria

- [ ] `c3d_affine_tool` succeeds
   or
- [ ] 'single_step_resampling' is explicitly disallowed for 3dvolreg

### Screenshots

_No response_

### C-PAC version

v1.8.4-dev

### Container platform

Singularity

### Docker and/or Singularity version(s)

Singularity 3.8.5-2.el7

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by shnizzedy**
## Fixes

Resolves #1642 by @shnizzedy
Resolves #1702 by @shnizzedy 

## Description

[Google Doc: `pipeline_config_rbc-options.yml`](https://docs.google.com/document/d/12FwkQt5CO3GZCIXRuAPLMa3xJsFiJTQ3hpP0eNKFSGw/edit)

## Checklist

- [x] My pull request has a descriptive title (not a vague title like `Update index.md`).
- [x] My pull request targets the `develop-1.8.4` branch of the repository. 
- [x] My commit messages follow best practices.
- [x] My code follows the established code style of the repository.
- [x] I added tests for the changes I made (if applicable).
- [x] I updated the changelog.
- [x] I added or updated documentation (if applicable).
- [x] I tried running the project locally and verified that there are no visible errors.

## Developer Certificate of Origin

<details>
<summary>Developer Certificate of Origin</summary>

```
Developer Certificate of Origin
Version 1.1

Copyright (C) 2004, 2006 The Linux Foundation and its contributors.
1 Letterman Drive
Suite D4700
San Francisco, CA, 94129

Everyone is permitted to copy and distribute verbatim copies of this
license document, but changing it is not allowed.


Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.
```

</details>

### CODE REVIEW

**Comment by shnizzedy** [comment]
Some crashes to resolve @ 0f335db, like:

```Python
Node: cpac_sub-colornest035_ses-1.qcxcp_222
Working directory: /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/qcxcp_222

Node inputs:

bold2t1w_mask = <undefined>
bold2template_mask = <undefined>
censor_indices = []
desc = preproc
dvars = <undefined>
dvars_after = <undefined>
fdj_after = <undefined>
final_func = <undefined>
framewise_displacement_jenkinson = <undefined>
function_str = CPAC.qc.xcp.generate_xcp_qc
movement_parameters = <undefined>
original_func = <undefined>
t1w_mask = <undefined>
template = <undefined>
template_mask = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/code/CPAC/pipeline/nipype_pipeline_engine/engine.py", line 388, in run
    return super().run(updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 419, in run
    runtime = self._run_interface(runtime)
  File "/code/CPAC/utils/interfaces/function/function.py", line 152, in _run_interface
    out = function_handle(**args)
  File "/code/CPAC/qc/xcp.py", line 298, in generate_xcp_qc
    template_mask=template_mask)
  File "/code/CPAC/qc/qcmetrics.py", line 15, in regisQ
    'normDice': [dc(bold2template_mask, template_mask)],
  File "/code/CPAC/qc/qcmetrics.py", line 61, in dc
    intersection = np.count_nonzero(input1 & input2)
ValueError: operands could not be broadcast together with shapes (196,234,198) (182,218,182) 
```

---

`/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/qcxcp_222/_report/report.rst`:
> Node: qcxcp_222 (interfaces)
> ============================
> 
> 
>  Hierarchy : cpac_sub-colornest035_ses-1.qcxcp_222
>  Exec ID : qcxcp_222.a0
> 
> 
> Original Inputs
> ---------------
> 
> 
> * bold2t1w_mask : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/binarize_bold_to_T1w_mask_222/uni_masked_flirt_maths.nii.gz
> * bold2template_mask : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz
> * censor_indices : []
> * desc : preproc
> * dvars : /outputs/working/cpac_sub-colornest035_ses-1/gen_motion_stats_111/_scan_rest_run-01/cal_DVARS_strip/dvars_strip.1D
> * dvars_after : /outputs/working/cpac_sub-colornest035_ses-1/motion_stats-after_222/_scan_rest_run-01/cal_DVARS_strip/dvars_strip.1D
> * fdj_after : /outputs/working/cpac_sub-colornest035_ses-1/motion_stats-after_222/_scan_rest_run-01/calculate_FDJ/FD_J.1D
> * final_func : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/func_extract_brain_107/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc_despike_tshift_resample_calc.nii.gz
> * framewise_displacement_jenkinson : /outputs/working/cpac_sub-colornest035_ses-1/gen_motion_stats_111/_scan_rest_run-01/calculate_FDJ/FD_J.1D
> * function_str : CPAC.qc.xcp.generate_xcp_qc
> * movement_parameters : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/oned_concat_86/MD5E-s43982431--4505293d1740413480db269995b35cf6_calc.1D
> * original_func : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds/inputs/data/.git/annex/objects/VJ/5F/MD5E-s43982431--4505293d1740413480db269995b35cf6.nii.gz/MD5E-s43982431--4505293d1740413480db269995b35cf6.nii.gz
> * space_T1w_bold : /outputs/working/cpac_sub-colornest035_ses-1/func_to_anat_bbreg_124/_scan_rest_run-01/bbreg_func_to_anat/uni_masked_flirt.nii.gz
> * t1w_mask : /outputs/working/cpac_sub-colornest035_ses-1/anat_skullstrip_ants/atropos_wf/copy_xform/09_relabel_wm_mask_xform.nii.gz
> * template : /outputs/working/cpac_sub-colornest035_ses-1/resampled_T1w-brain-template-funcreg/T1w-brain-template-funcreg/tpl-MNI152NLin2009cAsym_res-02_T1w_reference_resample.nii.gz
> * template_mask : /usr/share/data/fsl-mni152-templates/MNI152_T1_1mm_brain_mask.nii.gz
> 

---

I thought maybe something was going wrong with resampling bold to T1w, but it looks okay to me:

`/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/_report/report.rst`:
> Node: resample_bold_to_T1w_mask_222 (afni)
> ==========================================
> 
> 
>  Hierarchy : cpac_sub-colornest035_ses-1.resample_bold_to_T1w_mask_222
>  Exec ID : resample_bold_to_T1w_mask_222.a0
> 
> 
> Original Inputs
> ---------------
> 
> 
> * args : <undefined>
> * environ : {}
> * in_file : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz
> * master : <undefined>
> * num_threads : 1
> * orientation : <undefined>
> * out_file : <undefined>
> * outputtype : NIFTI_GZ
> * resample_mode : NN
> * voxel_size : (1.0, 1.0, 1.0)
> 
> 
> Execution Inputs
> ----------------
> 
> 
> * args : <undefined>
> * environ : {}
> * in_file : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz
> * master : <undefined>
> * num_threads : 1
> * orientation : <undefined>
> * out_file : <undefined>
> * outputtype : NIFTI_GZ
> * resample_mode : NN
> * voxel_size : (1.0, 1.0, 1.0)
> 
> 
> Execution Outputs
> -----------------
> 
> 
> * out_file : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz
> 
> 
> Runtime info
> ------------
> 
> 
> * cmdline : 3dresample -prefix ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz -rmode NN -dxyz 1.000000 1.000000 1.000000 -inset /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz
> * cpu_percent : 132.8
> * duration : 0.670881
> * hostname : 2115fmn032
> * mem_peak_gb : 0.25716781640625
> * prev_wd : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds
> * working_dir : /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222
> 
> 
> Terminal output
> ~~~~~~~~~~~~~~~
> 
> 
>  
> 
> 
> Terminal - standard output
> ~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
>  
> 
> 
> Terminal - standard error
> ~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 
>  ** AFNI converts NIFTI_datatype=64 (FLOAT64) in file /outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans.nii.gz to FLOAT32
>      Warnings of this type will be muted for this session.
>      Set AFNI_NIFTI_TYPE_WARN to YES to see them all, NO to see none.
> 
> 
> Environment
> ~~~~~~~~~~~
> 
> 
> * ANTSPATH : /usr/lib/ants
> * C3DPATH : /opt/c3d/
> * FIX_VERTEX_AREA : 
> * FREESURFER_HOME : /usr/lib/freesurfer
> * FSFAST_HOME : /usr/lib/freesurfer/fsfast
> * FSF_OUTPUT_FORMAT : nii.gz
> * FSLBROWSER : /etc/alternatives/x-www-browser
> * FSLDIR : /usr/share/fsl/5.0
> * FSLLOCKDIR : 
> * FSLMACHINELIST : 
> * FSLMULTIFILEQUIT : TRUE
> * FSLOUTPUTTYPE : NIFTI_GZ
> * FSLREMOTECALL : 
> * FSLTCLSH : /usr/bin/tclsh
> * FSLWISH : /usr/bin/wish
> * FSL_BIN : /usr/share/fsl/5.0/bin
> * FSL_DIR : /usr/share/fsl/5.0
> * FS_OVERRIDE : 0
> * FUNCTIONALS_DIR : /usr/lib/freesurfer/sessions
> * HOME : /cbica/projects/RBC
> * ITK_GLOBAL_DEFAULT_NUMBER_OF_THREADS : 1
> * KMP_DUPLICATE_LIB_OK : True
> * KMP_INIT_AT_FORK : FALSE
> * LANG : C
> * LC_ALL : en_US.UTF-8
> * LD_LIBRARY_PATH : /usr/lib/fsl/5.0::/.singularity.d/libs
> * LOCAL_DIR : /usr/lib/freesurfer/local
> * MINC_BIN_DIR : /usr/lib/freesurfer/mni/bin
> * MINC_LIB_DIR : /usr/lib/freesurfer/mni/lib
> * MKL_NUM_THREADS : 1
> * MNI_DATAPATH : /usr/lib/freesurfer/mni/data
> * MNI_DIR : /usr/lib/freesurfer/mni
> * MNI_PERL5LIB : /usr/lib/freesurfer/mni/share/perl5
> * MSMBINDIR : /opt/msm/Ubuntu
> * NIPYPE_NO_ET : 1
> * NO_FSFAST : 1
> * OMP_NUM_THREADS : 1
> * OS : Linux
> * PATH : /usr/lib/freesurfer/bin:/usr/lib/freesurfer/fsfast/bin:/usr/lib/freesurfer/tktools:/usr/share/fsl/5.0/bin:/usr/lib/fsl/5.0:/usr/lib/freesurfer/mni/bin:/usr/lib/freesurfer/bin:/usr/local/miniconda/bin:/opt/ICA-AROMA:/usr/lib/ants:/opt/afni:/opt/c3d//bin:/root/.npm-packages/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/msm/Ubuntu
> * PERL5LIB : /usr/lib/freesurfer/mni/share/perl5
> * POSSUMDIR : /usr/share/fsl/5.0
> * PROMPT_COMMAND : PS1="Singularity> "; unset PROMPT_COMMAND
> * PWD : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds
> * SHLVL : 1
> * SINGULARITY_APPNAME : 
> * SINGULARITY_BIND : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds,/cbica/comp_space/RBC/job-59323-sub-colornest035/ds/sub-colornest035_outputs:/outputs
> * SINGULARITY_COMMAND : run
> * SINGULARITY_CONTAINER : /cbica/comp_space/RBC/job-59323-sub-colornest035/ds/pennlinc-containers/.datalad/environments/cpac-1-8-4-dev/image
> * SINGULARITY_ENVIRONMENT : /.singularity.d/env/91-environment.sh
> * SINGULARITY_NAME : image
> * SUBJECTS_DIR : /usr/lib/freesurfer/subjects
> * TERM : 
> * _ : /code/run.py
> 

---

And the voxel size matches but the dimensions don't:
```Python
>>> import nibabel as nib
>>> bold2template_mask = nib.load('/outputs/working/cpac_sub-colornest035_ses-1/_scan_rest_run-01/resample_bold_to_T1w_mask_222/ref_bold_corrected_brain_mask_maths_trans_resample.nii.gz')
>>> template_mask = nib.load('/usr/share/data/fsl-mni152-templates/MNI152_T1_1mm_brain_mask.nii.gz')
>>> bold2template_mask.shape
(196, 234, 198)
>>> template_mask.shape
(182, 218, 182)
>>> print(bold2template_mask.header.get_zooms())
(1.0, 1.0, 1.0)
>>> print(template_mask.header.get_zooms())
(1.0, 1.0, 1.0)
```

**Comment by shnizzedy** [comment]
:point_up_2: 
> `bold2t1w_mask` is currently `'space-T1w_desc-mean_bold'` → `fslmaths -bin` → resample to `resolution_for_anat`

**Comment by shnizzedy** [comment]
Seems to be hitting https://github.com/FCP-INDI/C-PAC/issues/996 or something like it more often with this updated config, for both of these regressors:


[crash-20220405-180135-jclucas-build_nuisance_regressors.a0-18359279-7d06-4922-aa06-4a301d5ddb0d.txt](https://github.com/FCP-INDI/C-PAC/files/8421559/crash-20220405-180135-jclucas-build_nuisance_regressors.a0-18359279-7d06-4922-aa06-4a301d5ddb0d.txt)
[crash-20220405-180139-jclucas-build_nuisance_regressors.a0-db15627d-d62d-47df-95da-283fb6eac933.txt](https://github.com/FCP-INDI/C-PAC/files/8421561/crash-20220405-180139-jclucas-build_nuisance_regressors.a0-db15627d-d62d-47df-95da-283fb6eac933.txt)
[crash-20220405-191434-jclucas-build_nuisance_regressors.a0-55761957-2902-4e01-bcf9-b8e4d7cccc88.txt](https://github.com/FCP-INDI/C-PAC/files/8421562/crash-20220405-191434-jclucas-build_nuisance_regressors.a0-55761957-2902-4e01-bcf9-b8e4d7cccc88.txt)
[crash-20220405-191435-jclucas-build_nuisance_regressors.a0-3f2f9170-f0e8-4380-a979-8a2c3b15e397.txt](https://github.com/FCP-INDI/C-PAC/files/8421563/crash-20220405-191435-jclucas-build_nuisance_regressors.a0-3f2f9170-f0e8-4380-a979-8a2c3b15e397.txt)
[crash-20220405-191443-jclucas-build_nuisance_regressors.a1-e58e2fdd-0455-4947-be95-9c784fed8ba3.txt](https://github.com/FCP-INDI/C-PAC/files/8421564/crash-20220405-191443-jclucas-build_nuisance_regressors.a1-e58e2fdd-0455-4947-be95-9c784fed8ba3.txt)
[crash-20220405-191443-jclucas-build_nuisance_regressors.a1-ffaf7100-cd86-4d6c-864f-71e8c1542ef9.txt](https://github.com/FCP-INDI/C-PAC/files/8421565/crash-20220405-191443-jclucas-build_nuisance_regressors.a1-ffaf7100-cd86-4d6c-864f-71e8c1542ef9.txt)

**Comment by shnizzedy** [comment]
Eh, the variant thing didn't work as expected on the first try, so I [dropped it for now](https://github.com/FCP-INDI/C-PAC/pull/1683/commits/e9bef54d19ad57dd1275ab06ec457843d7f77c89)

I _think_ everything else looks good:

`nuisance_regressors_generation_Regressor-with-GSR`:
|sub         |ses|task|run|desc   |variant|space              |meanFD            |relMeansRMSMotion|relMaxRMSMotion  |meanDVInit        |meanDVFinal       |nVolCensored|nVolsRemoved|motionDVCorrInit   |motionDVCorrFinal  |coregDice         |coregJaccard     |coregCrossCorr    |coregCoverage     |normDice          |normJaccard       |normCrossCorr     |normCoverage    |
|------------|---|----|---|-------|-------|-------------------|------------------|-----------------|-----------------|------------------|------------------|------------|------------|-------------------|-------------------|------------------|-----------------|------------------|------------------|------------------|------------------|------------------|----------------|
|colornest035|1  |rest|1  |preproc|       |MNI152NLin2009cAsym|30.758775690714288|22.6353383576661 |27.03189190585816|20.332534685082873|10.633097922651935|0           |2           |0.36294128582125973|0.28603158641592874|0.9013807402973742|0.820466901828537|0.8872974396692739|0.9071687684019492|0.9173771609327611|0.8473654238840469|0.8941968646719608|0.92466603197305|


`nuisance_regressors_generation_Regressor-with-aCompCor`:

|sub         |ses|task|run|desc   |variant|space              |meanFD            |relMeansRMSMotion|relMaxRMSMotion  |meanDVInit        |meanDVFinal       |nVolCensored|nVolsRemoved|motionDVCorrInit   |motionDVCorrFinal  |coregDice         |coregJaccard     |coregCrossCorr    |coregCoverage     |normDice          |normJaccard       |normCrossCorr     |normCoverage    |
|------------|---|----|---|-------|-------|-------------------|------------------|-----------------|-----------------|------------------|------------------|------------|------------|-------------------|-------------------|------------------|-----------------|------------------|------------------|------------------|------------------|------------------|----------------|
|colornest035|1  |rest|1  |preproc|       |MNI152NLin2009cAsym|30.823812175000004|24.432894977722572|26.72842184847433|20.332534685082873|9.763720895027623 |0           |2           |0.36294128582125973|0.349327942683046  |0.9013807402973742|0.820466901828537|0.8872974396692739|0.9071687684019492|0.9173771609327611|0.8473654238840469|0.8941968646719608|0.92466603197305|


[quality.zip](https://github.com/FCP-INDI/C-PAC/files/8524730/quality.zip)

**Review by sgiavasis — APPROVED** [review]

**Pull request merged**
